version: '3.4'
services:
  portainer:
    image: portainer/portainer
    container_name: ws-portainer
    restart: always
    ports:
        - 9095:9000
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - atlassian

  jira:
    image: atlassian/jira-software:latest
    restart: always
    ports:
        - 8089:8080
    volumes:
      - jira-data:/var/atlassian/jira
    networks:
      - atlassian

  confluence:
    image: atlassian/confluence-server:latest
    restart: always
    ports:
        - 8090:8090
    volumes:
      - confluence-data:/var/atlassian/confluence
    networks:
      - atlassian

  database:
    image: postgres:12.2
    container_name: postgres
    restart: always
    ports:
        - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=confluencedb
      - POSTGRES_PASSWORD=verybigsecretrootpassword
      - POSTGRES_DB=confluencedb
    networks:
      - atlassian

  # nginx:
  #   image: nginx
  #   restart: always
  #   ports:
  #     - "80:80"
  #   volumes:
  #   - ./:/src
  #   command: ./src/scripts/run_nginx.sh
  #   environment:
  #     - DOMAIN
  #   networks:
  #   - atlassian

volumes:
  jira-data:
  confluence-data:
  db-data:
networks:
    atlassian:
        driver: bridge