version: '3.4'
services:
  portainer:
    image: portainer/portainer
    container_name: ws-portainer
    restart: always
    ports:
        - 9095:9000
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - atlassian

  jira:
    image: atlassian/jira-software:latest
    restart: always
    ports:
        - 8080:8080
    links:
      - database
    volumes:
      - jira-data:/var/atlassian/jira
    networks:
      - atlassian

  confluence:
    image: atlassian/confluence-server:latest
    restart: always
    ports:
        - 8090:8090
    links:
      - database
    volumes:
      - confluence-data:/var/atlassian/confluence
    networks:
      - atlassian

  # bitbucket:
  #   image: atlassian/bitbucket-server:latest
  #   restart: always
  #   links:
  #     - database
  #   volumes:
  #     - bitbucket-data:/var/atlassian/application-data/bitbucket
  database:
    image: postgres:12.2
    container_name: postgres
    restart: always
    ports:
        - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=confluencedb
      - POSTGRES_PASSWORD=verybigsecretrootpassword
      - POSTGRES_DB=confluencedb
    networks:
      - atlassian

  nginx:
    image: nginx
    restart: always
    ports:
      - "80:80"
    links:
      - jira
      - confluence
    volumes:
    - ./:/src
    command: ./src/scripts/run_nginx.sh
    environment:
      - DOMAIN
    networks:
    - atlassian
 ##### jenkins && jfog 
  # myjenkins:
  #     image: jenkinsci/blueocean
  #     container_name: myjenkins
  #     restart: always
  #     user: root
  #     ports:
  #         - 50000:50000
  #         - 9080:8080
  #     volumes:
  #         - /var/run/docker.sock:/var/run/docker.sock   
  #         - jenkins-data:/var/jenkins_home 
   
  # myjfrog:
  #     image: docker.bintray.io/jfrog/artifactory-oss
  #     container_name: myjfrog
  #     restart: always
  #     ports:
  #         - 8081:8081
  #     volumes:
  #         - /var/run/docker.sock:/var/run/docker.sock   

volumes:
  jira-data:
  confluence-data:
#  bitbucket-data:
  db-data:
#  jenkins-data:
networks:
    atlassian:
        driver: bridge