version: '3.4'
services:
  portainer:
      image: portainer/portainer
      container_name: ws-portainer
      restart: always
      ports:
          - 9095:9000
      volumes:
          - /var/run/docker.sock:/var/run/docker.sock
 
  jira:
    image: atlassian/jira-software:8.5.2
    restart: always
    links:
      - database
    volumes:
      - jira-data:/var/atlassian/jira

  confluence:
    image: atlassian/confluence-server:6.6.15
    restart: always
    links:
      - database
    volumes:
      - confluence-data:/var/atlassian/confluence

  # bitbucket:
  #   image: atlassian/bitbucket-server:latest
  #   restart: always
  #   links:
  #     - database
  #   volumes:
  #     - bitbucket-data:/var/atlassian/application-data/bitbucket
  database:
    image: postgres:12.2
    container_name: postgres
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=confluencedb
      - POSTGRES_PASSWORD=verybigsecretrootpassword
      - POSTGRES_DB=confluencedb
  nginx:
    image: nginx
    restart: always
    ports:
      - "80:80"
    links:
      - jira
      - confluence
    volumes:
    - ./:/src
    command: ./src/scripts/run_nginx.sh
    environment:
    - DOMAIN
volumes:
  jira-data:
  confluence-data:
#  bitbucket-data:
  db-data:
