version: '3.4'
services:

  portainer:
      image: portainer/portainer
      container_name: ws-portainer
      restart: always
      ports:
          - 9095:9000
      volumes:
          - /var/run/docker.sock:/var/run/docker.sock
 
  jira:
    image: cptactionhank/atlassian-jira:8.5.2
    restart: always
    links:
      - database
    volumes:
      - jira-data:/var/atlassian/jira

  confluence:
    image: cptactionhank/atlassian-confluence:6.15.10
    restart: always
    links:
      - database
    volumes:
      - confluence-data:/var/atlassian/confluence

  bitbucket:
    image: atlassian/bitbucket-server:6.7.5
    restart: always
    links:
      - database
    volumes:
      - bitbucket-data:/var/atlassian/application-data/bitbucket
  database:
    image: postgres:11
    container_name: postgres
    restart: always
    volumes:
      - postgresqldata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=confluencedb
      - POSTGRES_PASSWORD=verybigsecretrootpassword
      - POSTGRES_DB=confluencedb
  nginx:
    image: nginx
    restart: always
    ports:
      - "80:80"
    links:
      - jira
      - confluence
      - bitbucket
    volumes:
    - ./:/src
    command: ./src/scripts/run_nginx.sh
    environment:
    - DOMAIN
volumes:
  jira-data:
  confluence-data:
  bitbucket-data:
  database-data:
