version: '3.8'
services:
  jira:
    build:
      context: jira/
    restart: always
    ports:
        - 8080:8080
        #- 8081:8081
    depends_on:
      - database
    #user: jira
    volumes:
      # - type: bind
      #   source: ./jira/config/server.xml
      #   target: /opt/atlassian/jira/conf/server.xml
      #   read_only: true
      #- ./jira/config/server.xml:/opt/atlassian/jira/conf/server.xml
      #- ./certs/cacerts:/var/atlassian/application-data/jira/cacerts
      #- ./jira/config/web.xml:/opt/atlassian/jira/conf/web.xml
      - jira-data:/var/atlassian/application-data/jira
    environment: 
      - TZ=Asia/Shanghai
    networks:
      localdevops: 
        ipv4_address: 172.30.0.2
    extra_hosts:
      - "jira.yuzhicloud.com:127.0.0.1"
      - "wiki.yuzhicloud.com:127.0.0.1"

  confluence:
    build:
      context: confluence/
    restart: always
    ports:
        - 8090:8090
      #  - 8443:8443
    depends_on:
      - database
    user: confluence
    volumes:
      # - type: bind
      #   source: ./confluence/config/server.xml
      #   target: /opt/atlassian/confluence/conf/server.xml
      #   read_only: true
      #- ./confluence/config/server.xml:/opt/atlassian/confluence/conf/server.xml:cached
      # - ./certs/cacerts:/var/atlassian/application-data/confluence/cacerts
      # - ./confluence/config/web.xml:/opt/atlassian/confluence/conf/web.xml
      # - ./confluence/config/web2.xml:/opt/atlassian/confluence/confluence/WEB-INF/web.xml
      - confluence-data:/var/atlassian/application-data/confluence
    environment: 
      - TZ=Asia/Shanghai
    networks:
      localdevops: 
        ipv4_address: 172.30.0.3
    extra_hosts:
      - "jira.yuzhicloud.com:127.0.0.1"
      - "wiki.yuzhicloud.com:127.0.0.1"
      - "postgres.yuzhicloud.com:127.0.0.1"

  database:
    image: postgres:12.4
    container_name: postgres
    restart: always
    ports:
        - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=devops
      - POSTGRES_PASSWORD=verybigsecretrootpassword
      - POSTGRES_DB=wiki
    networks:
      localdevops: 
        ipv4_address: 172.30.0.4
    extra_hosts:
      - "jira.yuzhicloud.com:127.0.0.1"
      - "wiki.yuzhicloud.com:127.0.0.1"

  nginx:
    image: nginx
    restart: always
    ports:
      - "80:80"
    links:
      - jira
      - confluence
    volumes:
      - ./:/src
    command: ./src/scripts/run_nginx.sh
    networks:
      localdevops: 
        ipv4_address: 172.30.0.5
    environment:
      - DOMAIN
      - TZ=Asia/Shanghai
  
  # gitlab:
  #   image: 'gitlab/gitlab-ee:latest'
  #   container_name: devops_gitlab
  #   restart: always
  #   hostname: 'gitlab.yuzhicloud.com'
  #   environment:
  #     GITLAB_OMNIBUS_CONFIG: |
  #       external_url 'https://gitlab.yuzhicloud.com'
  #       # Add any other gitlab.rb configuration here, each on its own line
  #   ports:
  #     - '80:80'
  #     - '443:443'
  #     - '22:22'
  #   volumes:
  #     - '$GITLAB_HOME/config:/etc/gitlab'
  #     - '$GITLAB_HOME/logs:/var/log/gitlab'
  #     - '$GITLAB_HOME/data:/var/opt/gitlab'

volumes:
  jira-data:
  confluence-data:
  db-data:
networks:
  localdevops:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16

      
